import { TenantBranding, Category, BusinessListing } from './types';

export const INITIAL_TENANTS: TenantBranding[] = [
  {
    id: 't-1',
    slug: 'nordible-index',
    name: 'Nordible Directory',
    tagline: {
      de: 'Ausgewählte Partner, innovative Tech-Unternehmen und erstklassige Gastronomie im kuratierten Branchenindex',
      en: 'Curated partners, innovative tech companies, and premier dining in our verified business index',
    },
    primaryColor: '#145BFF',
    accentColor: '#FF9F1A',
    logoText: '🌟 Nordible',
  },
  {
    id: 't-2',
    slug: 'nordic-tech',
    name: 'Nordic Tech & Design Index',
    tagline: {
      de: 'Entdecken Sie innovative IT-Agenturen, SaaS-Startups und Designstudios',
      en: 'Discover innovative IT agencies, SaaS startups, and design studios',
    },
    primaryColor: '#145BFF',
    accentColor: '#FF9F1A',
    logoText: '⚡ NordicHub',
  },
];

export const CATEGORIES: Category[] = [
  {
    id: 'cat-all',
    slug: 'all',
    name: { de: 'Alle Branchen', en: 'All Categories' },
    icon: 'Grid',
  },
  {
    id: 'cat-tech',
    slug: 'tech',
    name: { de: 'IT, Software & Medien', en: 'IT, Software & Media' },
    icon: 'Laptop',
  },
  {
    id: 'cat-food',
    slug: 'gastronomie',
    name: { de: 'Gastronomie & Food', en: 'Food & Dining' },
    icon: 'Utensils',
  },
  {
    id: 'cat-craft',
    slug: 'architektur-planung',
    name: { de: 'Architektur & Planung', en: 'Architecture & Planning' },
    icon: 'Hammer',
  },
  {
    id: 'cat-services',
    slug: 'immobilien-beratung',
    name: { de: 'Immobilien & Beratung', en: 'Real Estate & Consulting' },
    icon: 'Briefcase',
  },
];

export const MOCK_LISTINGS: BusinessListing[] = [
  {
    id: 'list-nordible',
    tenantId: 't-1',
    name: 'Nordible Technologies',
    categoryId: 'cat-tech',
    description: {
      de: 'Spezialisierte Software-Agentur für moderne Webplattformen, autonome KI-Agenten, automatisierte Workflows, Directory-Systeme und Cloud-Architekturen.',
      en: 'Bespoke software engineering firm specializing in high-performance web platforms, autonomous AI agents, automated workflows, and cloud architectures.',
    },
    address: 'Westhafen Tower, Speicherstraße 55',
    city: '60327 Frankfurt am Main',
    phone: '+49 69 9999 8888',
    website: 'https://nordible.co/',
    rating: 5.0,
    reviewCount: 38,
    isVerified: true,
    isOpenNow: true,
    hours: 'Mo - Fr: 09:00 - 18:00 Uhr',
  },
  {
    id: 'list-buns069',
    tenantId: 't-1',
    name: 'BUNS 069',
    categoryId: 'cat-food',
    description: {
      de: 'Frankfurts angesagter Smash Burger Hotspot – frische handgefertigte Brioche-Buns, regionales Premium-Rindfleisch, knusprige Fries und unverwechselbare Saucen.',
      en: 'Frankfurt’s premier smash burger hotspot – fresh handcrafted brioche buns, regional premium beef, crispy fries, and signature sauces.',
    },
    address: 'Berger Straße 82',
    city: '60316 Frankfurt am Main',
    phone: '+49 69 4003 5590',
    website: 'https://www.buns069.de/',
    rating: 4.9,
    reviewCount: 142,
    isVerified: true,
    isOpenNow: true,
    hours: 'Mo - So: 12:00 - 22:00 Uhr',
  },
  {
    id: 'list-shams',
    tenantId: 't-1',
    name: 'Shams Consult Architektur und Stadtplanung',
    categoryId: 'cat-craft',
    description: {
      de: 'Renommiertes Büro für Architektur und Stadtplanung mit Fokus auf absolute Detailgenauigkeit, nachhaltigen Städtebau, Projektentwicklung und digitale Workflows.',
      en: 'Renowned architecture and urban planning studio focusing on precision execution, sustainable urban design, innovative development, and modern workflows.',
    },
    address: 'Mainzer Landstraße 180',
    city: '60327 Frankfurt am Main',
    phone: '+49 69 7430 8820',
    website: 'https://shams-consult.de/',
    rating: 5.0,
    reviewCount: 26,
    isVerified: true,
    isOpenNow: true,
    hours: 'Mo - Fr: 08:30 - 17:30 Uhr',
  },
  {
    id: 'list-bombay',
    tenantId: 't-1',
    name: 'Bombay Studio',
    categoryId: 'cat-tech',
    description: {
      de: 'Internationales Kreativ- und Produktionsstudio für Filmproduktionen, Markenidentität, High-End Visuals, Video-Edits und multimediales Storytelling.',
      en: 'International creative and production studio delivering high-end film production, brand identity, visual storytelling, and digital media.',
    },
    address: 'Studio Hub, Andheri West',
    city: 'Mumbai & Global',
    phone: '+91 22 2673 1100',
    website: 'https://bombaystudio.in/',
    rating: 4.9,
    reviewCount: 31,
    isVerified: true,
    isOpenNow: true,
    hours: 'Mo - Sa: 10:00 - 19:00 Uhr',
  },
  {
    id: 'list-weber',
    tenantId: 't-1',
    name: 'Manuela Weber Immobilien',
    categoryId: 'cat-services',
    description: {
      de: 'Zertifizierte und persönliche Immobilienmaklerin für Rödermark, Dietzenbach und den Kreis Offenbach. Qualifizierte Wertermittlung, Verkauf und Vermietung von Immobilien.',
      en: 'Certified and dedicated real estate agency for Rödermark, Dietzenbach, and the Offenbach district. Qualified valuations, property sales, and rentals.',
    },
    address: 'Dieburger Straße 40',
    city: '63322 Rödermark',
    phone: '+49 6074 9198 00',
    website: 'https://www.manuela-weber.de/',
    rating: 4.9,
    reviewCount: 44,
    isVerified: true,
    isOpenNow: true,
    hours: 'Mo - Fr: 09:00 - 18:00 Uhr',
  },
];
