import { TenantBranding, Category, BusinessListing } from './types';

export const INITIAL_TENANTS: TenantBranding[] = [
  {
    id: 't-1',
    slug: 'nordible-index',
    name: 'Nordible for Businesses',
    tagline: {
      de: 'Das globale Branchenverzeichnis für alle Unternehmensarten weltweit',
      en: 'The Global Business Directory for all types of businesses across the world',
    },
    primaryColor: '#145BFF',
    accentColor: '#FF9F1A',
    logoText: '🌟 Nordible for Businesses',
  },
  {
    id: 't-2',
    slug: 'nordic-tech',
    name: 'Nordic Tech & Design Index',
    tagline: {
      de: 'Entdecken Sie innovative IT-Agenturen, SaaS-Startups und Designstudios',
      en: 'Discover innovative IT agencies, SaaS startups, and design studios',
    },
    primaryColor: '#145BFF',
    accentColor: '#FF9F1A',
    logoText: '⚡ NordicHub',
  },
];

export const CATEGORIES: Category[] = [
  {
    id: 'cat-all',
    slug: 'all',
    name: { de: 'Alle Branchen', en: 'All Categories' },
    icon: 'Grid',
  },
  {
    id: 'cat-tech',
    slug: 'tech',
    name: { de: 'IT, Software & Medien', en: 'IT, Software & Media' },
    icon: 'Laptop',
  },
  {
    id: 'cat-craft',
    slug: 'architektur-planung',
    name: { de: 'Architektur & Planung', en: 'Architecture & Planning' },
    icon: 'Hammer',
  },
  {
    id: 'cat-food',
    slug: 'gastronomie',
    name: { de: 'Gastronomie & Food', en: 'Food & Dining' },
    icon: 'Utensils',
  },
  {
    id: 'cat-services',
    slug: 'immobilien-beratung',
    name: { de: 'Immobilien, Finanzen & Beratung', en: 'Real Estate, Finance & Consulting' },
    icon: 'Briefcase',
  },
  {
    id: 'cat-health',
    slug: 'gesundheit-wellness',
    name: { de: 'Gesundheit & Medizin', en: 'Healthcare & Wellness' },
    icon: 'Heart',
  },
  {
    id: 'cat-retail',
    slug: 'handel-ecommerce',
    name: { de: 'Handel & E-Commerce', en: 'Retail & E-Commerce' },
    icon: 'ShoppingBag',
  },
  {
    id: 'cat-industry',
    slug: 'industrie-bau',
    name: { de: 'Industrie, Fertigung & Handwerk', en: 'Industry & Craftsmanship' },
    icon: 'Factory',
  },
];

export const MOCK_LISTINGS: BusinessListing[] = [
  {
    id: 'list-nordible',
    tenantId: 't-1',
    name: 'Nordible Technologies',
    categoryId: 'cat-tech',
    description: {
      de: 'Spezialisierte Software-Engineering-Firma für moderne Webplattformen, autonome KI-Agenten, automatisierte Workflows, Directory-Systeme und Cloud-Architekturen.',
      en: 'Bespoke software engineering firm specializing in high-performance web platforms, autonomous AI agents, automated workflows, and cloud architectures.',
    },
    address: 'Breitlacherstraße 101',
    city: '60489 Frankfurt am Main',
    phone: '+49 1521 1065739',
    website: 'https://nordible.co/',
    logoUrl: 'https://nordible.co/apple-touch-icon.png',
    rating: 5.0,
    reviewCount: 38,
    isVerified: true,
    isOpenNow: true,
    hours: 'Mo - Fr: 09:00 - 18:00 Uhr',
  },
  {
    id: 'list-bombay',
    tenantId: 't-1',
    name: 'Bombay Studio',
    categoryId: 'cat-craft',
    description: {
      de: 'Renommiertes Luxus-Architektur- und schlüsselfertiges Interior-Design-Studio in Mumbai unter der Leitung von Principal Architect Ar. Aakhir Choudhary. Über 30 Jahre Tradition und mehr als 200 realisierte Premium-Projekte.',
      en: 'Premier luxury architecture and turnkey interior design firm in Mumbai led by Principal Architect Ar. Aakhir Choudhary. 30+ years pedigree delivering bespoke luxury residential and commercial spaces.',
    },
    address: 'Suite 402, Trade World B, BKC & Lower Parel',
    city: 'Mumbai, Maharashtra 400013',
    phone: '+91 707070 4181',
    website: 'https://bombaystudio.in/',
    logoUrl: 'https://bombaystudio.in/logo.png',
    rating: 4.9,
    reviewCount: 31,
    isVerified: true,
    isOpenNow: true,
    hours: 'Mo - Sa: 10:00 - 19:30 Uhr',
  },
  {
    id: 'list-buns069',
    tenantId: 't-1',
    name: 'BUNS 069',
    categoryId: 'cat-food',
    description: {
      de: 'Frankfurts und Offenbachs angesagter Smash Burger Hotspot – frische handgefertigte Brioche-Buns, regionales Premium-Rindfleisch, knusprige Loaded Fries und unverwechselbare Signature-Saucen.',
      en: 'Premier smash burger hotspot in the Frankfurt/Offenbach metro region – handcrafted brioche buns, regional premium beef, crispy loaded fries, and signature sauces.',
    },
    address: 'Offenbacher Straße 14',
    city: '63075 Offenbach am Main',
    phone: '+49 69 9131 1987',
    website: 'https://www.buns069.de/',
    logoUrl: 'https://mypartnerapi.de/img/images/customer_images/gallery/images/img_d9c18b88e85ece59_1790695192.webp',
    rating: 4.9,
    reviewCount: 142,
    isVerified: true,
    isOpenNow: true,
    hours: 'Mo - Di, Do: 16:00 - 01:30 | Fr - Sa: 16:00 - 02:00 | So: 16:00 - 00:00 (Mi: Geschlossen)',
  },
  {
    id: 'list-shams',
    tenantId: 't-1',
    name: 'Shams Consult Architektur und Stadtplanung',
    categoryId: 'cat-craft',
    description: {
      de: 'Renommiertes Büro für Architektur und Stadtplanung mit Fokus auf absolute Detailgenauigkeit, nachhaltigen Städtebau, anspruchsvolle Projektentwicklung und digitale Workflows.',
      en: 'Renowned architecture and urban planning studio focusing on precision execution, sustainable urban design, innovative development, and modern workflows.',
    },
    address: 'Carl-von-Noorden-Platz 5',
    city: '60596 Frankfurt am Main',
    phone: '+49 69 74 223 777',
    website: 'https://shams-consult.de/',
    logoUrl: 'https://shams-consult.de/logo.png',
    rating: 5.0,
    reviewCount: 26,
    isVerified: true,
    isOpenNow: true,
    hours: 'Mo - Fr: 08:30 - 17:30 Uhr',
  },
  {
    id: 'list-weber',
    tenantId: 't-1',
    name: 'Manuela Weber Immobilien',
    categoryId: 'cat-services',
    description: {
      de: 'Zertifizierte und persönliche Immobilienmaklerin für Rödermark, Dietzenbach und den Kreis Offenbach. Qualifizierte Wertermittlung, Verkauf und Vermietung von Immobilien mit jahrzehntelanger Expertise.',
      en: 'Certified and dedicated real estate agency for Rödermark, Dietzenbach, and the Offenbach district. Qualified valuations, property sales, and rentals.',
    },
    address: 'Robert-Bloch-Str. 21',
    city: '63322 Rödermark',
    phone: '+49 6074 922 615',
    website: 'https://www.manuela-weber.de/',
    rating: 4.9,
    reviewCount: 44,
    isVerified: true,
    isOpenNow: true,
    hours: 'Mo - Fr: 09:00 - 18:00 Uhr',
  },
];
